### PR TITLE
Brian

### PR DESCRIPTION
**Pull request by brianjohnpolasek**
Updated DndModule to include "Roll for Initiative" command, reverted appsettings.json which I changed for audio testing, added gitignore for all "vs" files.

### CODE REVIEW

**Comment by brianjohnpolasek** [comment]
The additions made to the .gitignore file should prevent future conflicts for ".vs" files, but for now please be aware that they are present in this pull request and should not be accepted.

**Comment by MichaelHHall** [comment]
So does the roll for initiative command just choose a random order? I don't think this is a good idea because people have initiative bonuses that won't be taken into account. Probably best to just let people roll for themselves. Interesting idea though!

**Comment by ct-bess** [comment]
nice

**Comment by ct-bess** [comment]
yo

**Comment by ct-bess** [comment]
Please provide updat e on merge request very much thank you that won't worry

**Comment by insyri** [comment]
pull request ⠮⠀⠗⠑⠟⠥⠑⠌⠀⠺⠀⠆⠀⠏⠥⠇⠇⠫

**Comment by ct-bess** [comment]
any ideas ? works on my machine

**Review by ct-bess — APPROVED** [review]
approved

**Review by insyri — APPROVED** [review]

**Comment by insyri** [comment]
approved

**Comment by JOBBIN9422** [comment]
> approved

thankls for input gamer

**Comment by ct-bess** [comment]
approved

best,

**Pull request closed without merging**
